name: Start Bot

on:

  push:

  workflow_dispatch:

jobs:

  bot:

    runs-on: ubuntu-latest

    steps:

      - name: Running bot in github action

        run:  git clone https://github.com/rootedcyber127-1/amirror;cd ami*;bash dep*h
